# Generated by Django 3.2.12 on 2023-12-17 08:58

from django.db import migrations, models
import filehost.models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=filehost.models.file_path),
        ),
    ]
