# Generated by Django 3.2.12 on 2023-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.SlugField(max_length=8),
        ),
    ]
