# Generated by Django 3.2.12 on 2023-12-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0003_alter_uploadedfile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file_name',
            new_name='slug',
        ),
    ]
