# Generated by Django 3.2.12 on 2023-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0004_rename_file_name_uploadedfile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('ARCHIVED', 'Archived')], default='LOCAL', max_length=8),
        ),
    ]
