# Generated by Django 3.2.12 on 2023-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0005_alter_uploadedfile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SHAREX', 'Sharex'), ('EMAIL', 'Email')], default='MANUAL', max_length=6),
        ),
    ]
