# Generated by Django 3.2.12 on 2023-12-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0006_uploadedfile_upload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='persistent',
            field=models.BooleanField(default=False),
        ),
    ]
