# Generated by Django 3.2.12 on 2023-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0007_uploadedfile_persistent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('ZIP', 'Zip'), ('FILE', 'File')], default='FILE', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='slug',
            field=models.SlugField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('ARCHIVED', 'Archived')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SHAREX', 'Sharex'), ('EMAIL', 'Email')], default='MANUAL', max_length=10),
        ),
    ]
