# Generated by Django 3.2.12 on 2023-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0008_auto_20231221_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('TEXT', 'Text'), ('FONT', 'Font'), ('MODEL', 'Model'), ('APPLICATION', 'Application'), ('FILE', 'File')], default='FILE', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('ARCHIVED', 'Archived')], default='LOCAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SHAREX', 'Sharex'), ('EMAIL', 'Email')], default='MANUAL', max_length=16),
        ),
    ]
