# Generated by Django 3.2.12 on 2023-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0009_auto_20231228_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('TEXT', 'Text'), ('FONT', 'Font'), ('MODEL', 'Model'), ('APPLICATION', 'Application')], default='FILE', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default="('application/octet-stream', None)", max_length=64),
        ),
    ]
