# Generated by Django 3.2.12 on 2024-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0010_auto_20231228_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SHAREX', 'Sharex'), ('EMAIL_ATTACHMENT', 'Email Attachment')], default='MANUAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
