# Generated by Django 3.2.12 on 2024-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0011_auto_20240128_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
