# Generated by Django 3.2.12 on 2024-01-29 03:46

from django.db import migrations, models
import filehost.models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0012_alter_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='slug',
            field=models.SlugField(default=filehost.models.random_slug, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
