# Generated by Django 3.2.12 on 2024-02-20 06:15

from django.db import migrations, models
import filehost.models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0013_alter_uploadedfile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(default='/MANUAL/FILE/UNKNOWN.TXT', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(null=True, upload_to=filehost.models.file_path),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=64),
        ),
    ]
