# Generated by Django 3.2.12 on 2024-02-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0014_auto_20240220_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='expiration_time',
            field=models.DateField(),
        ),
    ]
