# Generated by Django 3.2.12 on 2024-02-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0015_alter_uploadedfile_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
