# Generated by Django 3.2.12 on 2024-02-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0017_alter_uploadedfile_expiration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='expiration_time',
            new_name='expiration_date',
        ),
    ]
