# Generated by Django 3.2.12 on 2024-02-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0018_rename_expiration_time_uploadedfile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=128),
        ),
    ]
