# Generated by Django 3.2.12 on 2024-03-05 03:22

from django.db import migrations
import django_resized.forms
import filehost.models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0019_alter_uploadedfile_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[512, 512], upload_to="filehost.models.thumbnail_path"),
        ),
    ]
