# Generated by Django 3.2.12 on 2024-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0020_uploadedfile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail_path',
            field=models.CharField(default='/MANUAL/FILE/THUMBNAIL/UNKNOWN.PNG', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(default='/MANUAL/FILE/UNKNOWN.TXT', editable=False, max_length=64),
        ),
    ]
