# Generated by Django 3.2.12 on 2024-03-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0021_auto_20240305_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='thumbnail_path',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
