# Generated by Django 3.2.12 on 2024-03-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0022_alter_uploadedfile_thumbnail_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
