# Generated by Django 3.2.12 on 2024-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0023_alter_uploadedfile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('API', 'Api'), ('EMAIL_ATTACHMENT', 'Email Attachment')], default='MANUAL', max_length=16),
        ),
    ]
