# Generated by Django 3.2.12 on 2024-03-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0024_alter_uploadedfile_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default='UNKNOWN', max_length=128),
        ),
    ]
