# Generated by Django 3.2.12 on 2024-03-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0025_alter_uploadedfile_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
