# Generated by Django 3.2.12 on 2024-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0027_uploadedfile_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public - Anyone can view'), ('MEMBERS_ONLY', 'Members Only - Only registered accounts can view'), ('PRIVATE', 'Private - Only you can view')], default='PUBLIC', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('FILE', 'File - (default unknown file)'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('TEXT', 'Text'), ('FONT', 'Font'), ('MODEL', 'Model'), ('APPLICATION', 'Application')], default='FILE', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('LOCAL', 'Local - stored locally'), ('ARCHIVED', 'Archived - stored on NAS Archives (slower)')], default='LOCAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual - uploaded manually'), ('API', 'Api - uploaded via API endpoint'), ('EMAIL_ATTACHMENT', 'Email Attachment - uploaded via email server')], default='MANUAL', max_length=16),
        ),
    ]
