# Generated by Django 3.2.12 on 2024-04-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0028_auto_20240416_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS_ONLY', 'Members Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('ARCHIVED', 'Archived')], default='LOCAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('API', 'Api'), ('EMAIL_ATTACHMENT', 'Email Attachment')], default='MANUAL', max_length=16),
        ),
    ]
