# Generated by Django 3.2.12 on 2024-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0029_auto_20240416_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('TEXT', 'Text'), ('FONT', 'Font'), ('MODEL', 'Model'), ('APPLICATION', 'Application')], default='FILE', max_length=16),
        ),
    ]
