# Generated by Django 4.2.30 on 2026-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehost', '0030_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
